spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/protective_equipment_service_database
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /protectiveEquipment
  port: 8055